---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: precise64
    driver:
      box: precise64
      box_url: http://files.vagrantup.com/precise64.box

suites:
  - name: default
    run_list:
      - recipe[helloworld::default]
      - recipe[helloworld::nginx]
      - recipe[minitest-handler]
    attributes:
      helloworld:
        message: 'Hello from the kitchen'
      minitest:
        recipes:
          - helloworld
          - helloworld::nginx
